version: '3'

tasks:

  run:
    deps: [ buildweb ]
    cmds:
      - go run ./server.go

  buildproto:
    cmds:
      - protoc 
        --go_out=./src-go --go_opt=paths=source_relative 
        --go-grpc_out=./src-go --go-grpc_opt=paths=source_relative 
        --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" 
        --js_out="import_style=commonjs,binary:./src" 
        --ts_out=service=grpc-web:./src 
        ./proto/accountservice.proto
    env:
        PROTOC_GEN_TS_PATH: ./node_modules/.bin/protoc-gen-ts

  buildweb:
    cmds:
      - npm install
      - npm run build

  pushdocs:
    dir: './proto'
    cmds:
      - buf push

  buildcontainers:
    deps: [ buildweb ]
    cmds:
      - ko build --base-import-paths .
    env:
      KO_DEFAULTPLATFORMS: linux/arm64,linux/amd64
      KO_DOCKER_REPO: piha